development:
  adapter: mysql2
  encoding: utf8
  database: blogs_info_development
  pool: 5
  username: root
  password: root


test:
  adapter: mysql2
  encoding: utf8
  database: blogs_info_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: blogs_info_production
  pool: 5
  username: root
  password: root
